org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

## Environment
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.10
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1

## Mod
mod_group_id=com.mystanica.dreamlands
mod_id=dreamlands
mod_name=Dreamlands
mod_page_url=https://www.curseforge.com/minecraft/mc-mods/dreamlands
mod_github_url=https://github.com/jayhillx/Dreamlands
mod_issues_url=https://github.com/jayhillx/Dreamlands/issues
mod_license=All Rights Reserved
mod_version=1.0.2
mod_authors=Jay
mod_description=Escape reality in your dreamland.

# Other
jei_version=15.20.0.112