package com.mystanica.dreamlands.init;

import com.mystanica.dreamlands.Dreamlands;
import net.minecraft.core.registries.Registries;
import net.minecraft.network.chat.Component;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.ItemStack;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.RegistryObject;

public class DreamTabs {
    public static final DeferredRegister<CreativeModeTab> CREATIVE_TABS = DeferredRegister.create(Registries.CREATIVE_MODE_TAB, Dreamlands.modId);

    public static final RegistryObject<CreativeModeTab> DREAMLAND_TAB = CREATIVE_TABS.register("dreamland_tab", () -> CreativeModeTab.builder()
            .title(Component.translatable("itemGroup.dreamland"))
            .icon(() -> new ItemStack(DreamItems.PINK_MUSHROOM_BLOCK.get()))
            .displayItems((parameters, output) -> {
                output.accept(DreamItems.DREAMSTONE.get());
                output.accept(DreamItems.DREAMSTONE_STAIRS.get());
                output.accept(DreamItems.DREAMSTONE_SLAB.get());
                output.accept(DreamItems.DREAMSTONE_PRESSURE_PLATE.get());
                output.accept(DreamItems.DREAMSTONE_BUTTON.get());
                output.accept(DreamItems.DREAMSTONE_WALL.get());
                output.accept(DreamItems.COBBLED_DREAMSTONE.get());
                output.accept(DreamItems.COBBLED_DREAMSTONE_STAIRS.get());
                output.accept(DreamItems.COBBLED_DREAMSTONE_SLAB.get());
                output.accept(DreamItems.COBBLED_DREAMSTONE_WALL.get());
                output.accept(DreamItems.MOSSY_COBBLED_DREAMSTONE.get());
                output.accept(DreamItems.MOSSY_COBBLED_DREAMSTONE_STAIRS.get());
                output.accept(DreamItems.MOSSY_COBBLED_DREAMSTONE_SLAB.get());
                output.accept(DreamItems.MOSSY_COBBLED_DREAMSTONE_WALL.get());
                output.accept(DreamItems.DREAMSTONE_BRICKS.get());
                output.accept(DreamItems.DREAMSTONE_BRICK_STAIRS.get());
                output.accept(DreamItems.DREAMSTONE_BRICK_SLAB.get());
                output.accept(DreamItems.DREAMSTONE_BRICK_WALL.get());
                output.accept(DreamItems.CRACKED_DREAMSTONE_BRICKS.get());
                output.accept(DreamItems.CHISELED_DREAMSTONE_BRICKS.get());
                output.accept(DreamItems.MOSSY_DREAMSTONE_BRICKS.get());
                output.accept(DreamItems.MOSSY_DREAMSTONE_BRICK_STAIRS.get());
                output.accept(DreamItems.MOSSY_DREAMSTONE_BRICK_SLAB.get());
                output.accept(DreamItems.MOSSY_DREAMSTONE_BRICK_WALL.get());

                output.accept(DreamItems.DREAMY_GRASS_BLOCK.get());
                output.accept(DreamItems.DREAMY_DIRT_PATH.get());
                output.accept(DreamItems.DREAMY_DIRT.get());
                output.accept(DreamItems.DREAMY_GRASS.get());
                output.accept(DreamItems.TALL_DREAMY_GRASS.get());

                output.accept(DreamItems.DREAMY_MUSHROOM_BLOCK.get());
                output.accept(DreamItems.DREAMY_MUSHROOM.get());

                output.accept(DreamItems.PINK_MUSHROOM_BLOCK.get());
                output.accept(DreamItems.PINK_MUSHROOM.get());

                output.accept(DreamItems.FAIRY_ROSE_BUSH_LEAVES.get());
                output.accept(DreamItems.FAIRY_ROSE_BUSH.get());
                output.accept(DreamItems.LILAC_BUSH_LEAVES.get());
                output.accept(DreamItems.LILAC_BUSH.get());

                output.accept(DreamItems.WISTERIA.get());
                output.accept(DreamItems.GROUND_IVY.get());
                output.accept(DreamItems.CLOVERS.get());
                output.accept(DreamItems.WHITE_CLOVERS.get());
                output.accept(DreamItems.PINK_CLOVERS.get());
                output.accept(DreamItems.PETUNIA.get());
                output.accept(DreamItems.PERIWINKLE.get());
                output.accept(DreamItems.PINK_FOXGLOVE.get());
                output.accept(DreamItems.PINK_HYACINTH.get());
                output.accept(DreamItems.MAGENTA_HYACINTH.get());
                output.accept(DreamItems.PURPLE_HYACINTH.get());
                output.accept(DreamItems.VIOLETS.get());

                output.accept(DreamItems.FOREST_SHRUB_LEAVES.get());
                output.accept(DreamItems.FOREST_SHRUB.get());
                output.accept(DreamItems.FOREST_MOSS_BLOCK.get());
                output.accept(DreamItems.FOREST_MOSS_CARPET.get());
                ///output.accept(DreamItems.FOREST_GRASS.get());
                ///output.accept(DreamItems.TALL_FOREST_GRASS.get());
                output.accept(DreamItems.FOREST_MUSHROOM_BLOCK.get());
                output.accept(DreamItems.FOREST_MUSHROOM.get());

                output.accept(DreamItems.TOADSTOOL_BLOCK.get());
                output.accept(DreamItems.TOADSTOOL.get());

                output.accept(DreamItems.DREAMY_LEAVES.get());
                output.accept(DreamItems.DREAMY_SAPLING.get());
                output.accept(DreamItems.DREAMY_LOG.get());
                output.accept(DreamItems.DREAMY_WOOD.get());
                output.accept(DreamItems.STRIPPED_DREAMY_LOG.get());
                output.accept(DreamItems.STRIPPED_DREAMY_WOOD.get());
                output.accept(DreamItems.DREAMY_PLANKS.get());
                output.accept(DreamItems.DREAMY_STAIRS.get());
                output.accept(DreamItems.DREAMY_SLAB.get());
                output.accept(DreamItems.DREAMY_FENCE.get());
                output.accept(DreamItems.DREAMY_FENCE_GATE.get());
                output.accept(DreamItems.DREAMY_BUTTON.get());
                output.accept(DreamItems.DREAMY_PRESSURE_PLATE.get());
                output.accept(DreamItems.DREAMY_TRAPDOOR.get());
                output.accept(DreamItems.DREAMY_DOOR.get());
                output.accept(DreamItems.DREAMY_SIGN.get());
                output.accept(DreamItems.DREAMY_HANGING_SIGN.get());
                output.accept(DreamItems.DREAMY_BOAT.get());
                output.accept(DreamItems.DREAMY_CHEST_BOAT.get());

                ///output.accept(DreamItems.ASPEN_LEAVES.get());
                ///output.accept(DreamItems.ASPEN_SAPLING.get());
                ///output.accept(DreamItems.ASPEN_LOG.get());
                ///output.accept(DreamItems.ASPEN_WOOD.get());
                ///output.accept(DreamItems.STRIPPED_ASPEN_LOG.get());
                ///output.accept(DreamItems.STRIPPED_ASPEN_WOOD.get());
                ///output.accept(DreamItems.ASPEN_PLANKS.get());
                ///output.accept(DreamItems.ASPEN_STAIRS.get());
                ///output.accept(DreamItems.ASPEN_SLAB.get());
                ///output.accept(DreamItems.ASPEN_FENCE.get());
                ///output.accept(DreamItems.ASPEN_FENCE_GATE.get());
                ///output.accept(DreamItems.ASPEN_BUTTON.get());
                ///output.accept(DreamItems.ASPEN_PRESSURE_PLATE.get());
                ///output.accept(DreamItems.ASPEN_TRAPDOOR.get());
                ///output.accept(DreamItems.ASPEN_DOOR.get());
                ///output.accept(DreamItems.ASPEN_SIGN.get());
                ///output.accept(DreamItems.ASPEN_HANGING_SIGN.get());
                ///output.accept(DreamItems.ASPEN_BOAT.get());
                ///output.accept(DreamItems.ASPEN_CHEST_BOAT.get());

                output.accept(DreamItems.EVERGREEN_LEAVES.get());
                output.accept(DreamItems.EVERGREEN_SAPLING.get());
                output.accept(DreamItems.EVERGREEN_LOG.get());
                output.accept(DreamItems.EVERGREEN_WOOD.get());
                output.accept(DreamItems.STRIPPED_EVERGREEN_LOG.get());
                output.accept(DreamItems.STRIPPED_EVERGREEN_WOOD.get());
                output.accept(DreamItems.EVERGREEN_PLANKS.get());
                output.accept(DreamItems.EVERGREEN_STAIRS.get());
                output.accept(DreamItems.EVERGREEN_SLAB.get());
                output.accept(DreamItems.EVERGREEN_FENCE.get());
                output.accept(DreamItems.EVERGREEN_FENCE_GATE.get());
                output.accept(DreamItems.EVERGREEN_BUTTON.get());
                output.accept(DreamItems.EVERGREEN_PRESSURE_PLATE.get());
                output.accept(DreamItems.EVERGREEN_TRAPDOOR.get());
                output.accept(DreamItems.EVERGREEN_DOOR.get());
                output.accept(DreamItems.EVERGREEN_SIGN.get());
                output.accept(DreamItems.EVERGREEN_HANGING_SIGN.get());
                output.accept(DreamItems.EVERGREEN_BOAT.get());
                output.accept(DreamItems.EVERGREEN_CHEST_BOAT.get());

                output.accept(DreamItems.ETHEREAL_LEAVES.get());
                output.accept(DreamItems.ETHEREAL_SAPLING.get());
                output.accept(DreamItems.ETHEREAL_LOG.get());
                output.accept(DreamItems.ETHEREAL_WOOD.get());
                output.accept(DreamItems.STRIPPED_ETHEREAL_LOG.get());
                output.accept(DreamItems.STRIPPED_ETHEREAL_WOOD.get());
                output.accept(DreamItems.ETHEREAL_PLANKS.get());
                output.accept(DreamItems.ETHEREAL_STAIRS.get());
                output.accept(DreamItems.ETHEREAL_SLAB.get());
                output.accept(DreamItems.ETHEREAL_FENCE.get());
                output.accept(DreamItems.ETHEREAL_FENCE_GATE.get());
                output.accept(DreamItems.ETHEREAL_BUTTON.get());
                output.accept(DreamItems.ETHEREAL_PRESSURE_PLATE.get());
                output.accept(DreamItems.ETHEREAL_TRAPDOOR.get());
                output.accept(DreamItems.ETHEREAL_DOOR.get());
                output.accept(DreamItems.ETHEREAL_SIGN.get());
                output.accept(DreamItems.ETHEREAL_HANGING_SIGN.get());
                output.accept(DreamItems.ETHEREAL_BOAT.get());
                output.accept(DreamItems.ETHEREAL_CHEST_BOAT.get());

                output.accept(DreamItems.PINK_COTTON_CANDY_BLOCK.get());
                output.accept(DreamItems.PINK_COTTON_CANDY_SAPLING.get());
                output.accept(DreamItems.BLUE_COTTON_CANDY_BLOCK.get());
                output.accept(DreamItems.BLUE_COTTON_CANDY_SAPLING.get());
                output.accept(DreamItems.CANDY_LOG.get());
                output.accept(DreamItems.CANDY_WOOD.get());
                output.accept(DreamItems.STRIPPED_CANDY_LOG.get());
                output.accept(DreamItems.STRIPPED_CANDY_WOOD.get());
                output.accept(DreamItems.CANDY_PLANKS.get());
                output.accept(DreamItems.CANDY_STAIRS.get());
                output.accept(DreamItems.CANDY_SLAB.get());
                output.accept(DreamItems.CANDY_FENCE.get());
                output.accept(DreamItems.CANDY_FENCE_GATE.get());
                output.accept(DreamItems.CANDY_BUTTON.get());
                output.accept(DreamItems.CANDY_PRESSURE_PLATE.get());
                output.accept(DreamItems.CANDY_TRAPDOOR.get());
                output.accept(DreamItems.CANDY_DOOR.get());
                output.accept(DreamItems.CANDY_SIGN.get());
                output.accept(DreamItems.CANDY_HANGING_SIGN.get());
                output.accept(DreamItems.CANDY_BOAT.get());
                output.accept(DreamItems.CANDY_CHEST_BOAT.get());

                output.accept(DreamItems.WISTERIA_LEAVES.get());
                output.accept(DreamItems.WISTERIA_BLOSSOMS.get());
                output.accept(DreamItems.WISTERIA_SAPLING.get());
                output.accept(DreamItems.WISTERIA_LOG.get());
                output.accept(DreamItems.WISTERIA_WOOD.get());
                output.accept(DreamItems.STRIPPED_WISTERIA_LOG.get());
                output.accept(DreamItems.STRIPPED_WISTERIA_WOOD.get());
                output.accept(DreamItems.WISTERIA_PLANKS.get());
                output.accept(DreamItems.WISTERIA_STAIRS.get());
                output.accept(DreamItems.WISTERIA_SLAB.get());
                output.accept(DreamItems.WISTERIA_FENCE.get());
                output.accept(DreamItems.WISTERIA_FENCE_GATE.get());
                output.accept(DreamItems.WISTERIA_BUTTON.get());
                output.accept(DreamItems.WISTERIA_PRESSURE_PLATE.get());
                output.accept(DreamItems.WISTERIA_TRAPDOOR.get());
                output.accept(DreamItems.WISTERIA_DOOR.get());
                output.accept(DreamItems.WISTERIA_SIGN.get());
                output.accept(DreamItems.WISTERIA_HANGING_SIGN.get());
                output.accept(DreamItems.WISTERIA_BOAT.get());
                output.accept(DreamItems.WISTERIA_CHEST_BOAT.get());

                output.accept(DreamItems.MYSTICAL_LEAVES.get());
                output.accept(DreamItems.MYSTICAL_SAPLING.get());
                output.accept(DreamItems.MYSTICAL_LOG.get());
                output.accept(DreamItems.MYSTICAL_WOOD.get());
                output.accept(DreamItems.STRIPPED_MYSTICAL_LOG.get());
                output.accept(DreamItems.STRIPPED_MYSTICAL_WOOD.get());
                output.accept(DreamItems.MYSTICAL_PLANKS.get());
                output.accept(DreamItems.MYSTICAL_STAIRS.get());
                output.accept(DreamItems.MYSTICAL_SLAB.get());
                output.accept(DreamItems.MYSTICAL_FENCE.get());
                output.accept(DreamItems.MYSTICAL_FENCE_GATE.get());
                output.accept(DreamItems.MYSTICAL_BUTTON.get());
                output.accept(DreamItems.MYSTICAL_PRESSURE_PLATE.get());
                output.accept(DreamItems.MYSTICAL_TRAPDOOR.get());
                output.accept(DreamItems.MYSTICAL_DOOR.get());
                output.accept(DreamItems.MYSTICAL_SIGN.get());
                output.accept(DreamItems.MYSTICAL_HANGING_SIGN.get());
                output.accept(DreamItems.MYSTICAL_BOAT.get());
                output.accept(DreamItems.MYSTICAL_CHEST_BOAT.get());

                output.accept(DreamItems.MUSHROOM_STEM.get());
                output.accept(DreamItems.MUSHROOM_HYPHAE.get());
                output.accept(DreamItems.STRIPPED_MUSHROOM_STEM.get());
                output.accept(DreamItems.STRIPPED_MUSHROOM_HYPHAE.get());
                output.accept(DreamItems.MUSHROOM_PLANKS.get());
                output.accept(DreamItems.MUSHROOM_STAIRS.get());
                output.accept(DreamItems.MUSHROOM_SLAB.get());
                output.accept(DreamItems.MUSHROOM_FENCE.get());
                output.accept(DreamItems.MUSHROOM_FENCE_GATE.get());
                output.accept(DreamItems.MUSHROOM_BUTTON.get());
                output.accept(DreamItems.MUSHROOM_PRESSURE_PLATE.get());
                output.accept(DreamItems.MUSHROOM_TRAPDOOR.get());
                output.accept(DreamItems.MUSHROOM_DOOR.get());
                output.accept(DreamItems.MUSHROOM_SIGN.get());
                output.accept(DreamItems.MUSHROOM_HANGING_SIGN.get());
                output.accept(DreamItems.MUSHROOM_BOAT.get());
                output.accept(DreamItems.MUSHROOM_CHEST_BOAT.get());

                output.accept(DreamItems.DREAMY_MUSHROOM_SOUP.get());
                output.accept(DreamItems.MARSHMALLOW.get());
                output.accept(DreamItems.SMORE.get());

                output.accept(DreamItems.FAWN_SPAWN_EGG.get());
                output.accept(DreamItems.FOREST_FOX_SPAWN_EGG.get());
                output.accept(DreamItems.GNOME_SPAWN_EGG.get());
                output.accept(DreamItems.COTTON_CANDY_SHEEP_SPAWN_EGG.get());
            }).build()
    );

    ///public static final RegistryObject<CreativeModeTab> NIGHTMOOR_TAB = CREATIVE_TABS.register("nightmoor_tab", () -> CreativeModeTab.builder()
    ///        .title(Component.translatable("itemGroup.nightmoor"))
    ///        .icon(() -> new ItemStack(DreamItems.DREAMY_PLANKS.get()))
    ///        .displayItems((parameters, output) -> {
    ///            output.accept(DreamItems.GRIMSTONE.get());
    ///            output.accept(DreamItems.GRIMSTONE_STAIRS.get());
    ///            output.accept(DreamItems.GRIMSTONE_SLAB.get());
    ///            output.accept(DreamItems.GRIMSTONE_PRESSURE_PLATE.get());
    ///            output.accept(DreamItems.GRIMSTONE_BUTTON.get());
    ///            output.accept(DreamItems.GRIMSTONE_WALL.get());
    ///            output.accept(DreamItems.COBBLED_GRIMSTONE.get());
    ///            output.accept(DreamItems.COBBLED_GRIMSTONE_STAIRS.get());
    ///            output.accept(DreamItems.COBBLED_GRIMSTONE_SLAB.get());
    ///            output.accept(DreamItems.COBBLED_GRIMSTONE_WALL.get());
    ///            output.accept(DreamItems.MOSSY_COBBLED_GRIMSTONE.get());
    ///            output.accept(DreamItems.MOSSY_COBBLED_GRIMSTONE_STAIRS.get());
    ///            output.accept(DreamItems.MOSSY_COBBLED_GRIMSTONE_SLAB.get());
    ///            output.accept(DreamItems.MOSSY_COBBLED_GRIMSTONE_WALL.get());
    ///            output.accept(DreamItems.GRIMSTONE_BRICKS.get());
    ///            output.accept(DreamItems.GRIMSTONE_BRICK_STAIRS.get());
    ///            output.accept(DreamItems.GRIMSTONE_BRICK_SLAB.get());
    ///            output.accept(DreamItems.GRIMSTONE_BRICK_WALL.get());
    ///            output.accept(DreamItems.CRACKED_GRIMSTONE_BRICKS.get());
    ///            output.accept(DreamItems.CHISELED_GRIMSTONE_BRICKS.get());
    ///            output.accept(DreamItems.MOSSY_GRIMSTONE_BRICKS.get());
    ///            output.accept(DreamItems.MOSSY_GRIMSTONE_BRICK_STAIRS.get());
    ///            output.accept(DreamItems.MOSSY_GRIMSTONE_BRICK_SLAB.get());
    ///            output.accept(DreamItems.MOSSY_GRIMSTONE_BRICK_WALL.get());
    ///
    ///            output.accept(DreamItems.DREAMY_GRASS_BLOCK.get());
    ///            output.accept(DreamItems.DREAMY_DIRT_PATH.get());
    ///            output.accept(DreamItems.DREAMY_DIRT.get());
    ///            output.accept(DreamItems.DREAMY_SOIL.get());
    ///            output.accept(DreamItems.DREAMY_GRASS.get());
    ///            output.accept(DreamItems.TALL_DREAMY_GRASS.get());
    ///            output.accept(DreamItems.DREAMY_FERN.get());
    ///            output.accept(DreamItems.TALL_DREAMY_FERN.get());
    ///            output.accept(DreamItems.GLOOMY_MUSHROOM_BLOCK.get());
    ///            output.accept(DreamItems.GLOOMY_MUSHROOM.get());
    ///
    ///            output.accept(DreamItems.FOREST_SHRUB_LEAVES.get());
    ///            output.accept(DreamItems.FOREST_SHRUB.get());
    ///            output.accept(DreamItems.FOREST_MOSS_BLOCK.get());
    ///            output.accept(DreamItems.FOREST_MOSS_CARPET.get());
    ///            output.accept(DreamItems.FOREST_GRASS.get());
    ///            output.accept(DreamItems.TALL_FOREST_GRASS.get());
    ///            output.accept(DreamItems.FOREST_MUSHROOM_BLOCK.get());
    ///            output.accept(DreamItems.FOREST_MUSHROOM.get());
    ///
    ///            output.accept(DreamItems.GLOOMY_LEAVES.get());
    ///            output.accept(DreamItems.GLOOMY_SAPLING.get());
    ///            output.accept(DreamItems.GLOOMY_LOG.get());
    ///            output.accept(DreamItems.GLOOMY_WOOD.get());
    ///            output.accept(DreamItems.STRIPPED_GLOOMY_LOG.get());
    ///            output.accept(DreamItems.STRIPPED_GLOOMY_WOOD.get());
    ///            output.accept(DreamItems.GLOOMY_PLANKS.get());
    ///            output.accept(DreamItems.GLOOMY_STAIRS.get());
    ///            output.accept(DreamItems.GLOOMY_SLAB.get());
    ///            output.accept(DreamItems.GLOOMY_FENCE.get());
    ///            output.accept(DreamItems.GLOOMY_FENCE_GATE.get());
    ///            output.accept(DreamItems.GLOOMY_BUTTON.get());
    ///            output.accept(DreamItems.GLOOMY_PRESSURE_PLATE.get());
    ///            output.accept(DreamItems.GLOOMY_TRAPDOOR.get());
    ///            output.accept(DreamItems.GLOOMY_DOOR.get());
    ///            output.accept(DreamItems.GLOOMY_SIGN.get());
    ///            output.accept(DreamItems.GLOOMY_HANGING_SIGN.get());
    ///            output.accept(DreamItems.GLOOMY_BOAT.get());
    ///            output.accept(DreamItems.GLOOMY_CHEST_BOAT.get());
    ///
    ///            output.accept(DreamItems.GRIMWOOD_LEAVES.get());
    ///            output.accept(DreamItems.GRIMWOOD_SAPLING.get());
    ///            output.accept(DreamItems.GRIMWOOD_LOG.get());
    ///            output.accept(DreamItems.GRIMWOOD_WOOD.get());
    ///            output.accept(DreamItems.STRIPPED_GRIMWOOD_LOG.get());
    ///            output.accept(DreamItems.STRIPPED_GRIMWOOD_WOOD.get());
    ///            output.accept(DreamItems.GRIMWOOD_PLANKS.get());
    ///            output.accept(DreamItems.GRIMWOOD_STAIRS.get());
    ///            output.accept(DreamItems.GRIMWOOD_SLAB.get());
    ///            output.accept(DreamItems.GRIMWOOD_FENCE.get());
    ///            output.accept(DreamItems.GRIMWOOD_FENCE_GATE.get());
    ///            output.accept(DreamItems.GRIMWOOD_BUTTON.get());
    ///            output.accept(DreamItems.GRIMWOOD_PRESSURE_PLATE.get());
    ///            output.accept(DreamItems.GRIMWOOD_TRAPDOOR.get());
    ///            output.accept(DreamItems.GRIMWOOD_DOOR.get());
    ///            output.accept(DreamItems.GRIMWOOD_SIGN.get());
    ///            output.accept(DreamItems.GRIMWOOD_HANGING_SIGN.get());
    ///            output.accept(DreamItems.GRIMWOOD_BOAT.get());
    ///            output.accept(DreamItems.GRIMWOOD_CHEST_BOAT.get());
    ///
    ///            output.accept(DreamItems.DEAD_LEAVES.get());
    ///            output.accept(DreamItems.DEAD_SAPLING.get());
    ///            output.accept(DreamItems.DEAD_LOG.get());
    ///            output.accept(DreamItems.DEAD_WOOD.get());
    ///            output.accept(DreamItems.STRIPPED_DEAD_LOG.get());
    ///            output.accept(DreamItems.STRIPPED_DEAD_WOOD.get());
    ///            output.accept(DreamItems.DEAD_PLANKS.get());
    ///            output.accept(DreamItems.DEAD_STAIRS.get());
    ///            output.accept(DreamItems.DEAD_SLAB.get());
    ///            output.accept(DreamItems.DEAD_FENCE.get());
    ///            output.accept(DreamItems.DEAD_FENCE_GATE.get());
    ///            output.accept(DreamItems.DEAD_BUTTON.get());
    ///            output.accept(DreamItems.DEAD_PRESSURE_PLATE.get());
    ///            output.accept(DreamItems.DEAD_TRAPDOOR.get());
    ///            output.accept(DreamItems.DEAD_DOOR.get());
    ///            output.accept(DreamItems.DEAD_SIGN.get());
    ///            output.accept(DreamItems.DEAD_HANGING_SIGN.get());
    ///            output.accept(DreamItems.DEAD_BOAT.get());
    ///            output.accept(DreamItems.DEAD_CHEST_BOAT.get());
    ///
    ///            output.accept(DreamItems.PINE_LEAVES.get());
    ///            output.accept(DreamItems.PINE_SAPLING.get());
    ///            output.accept(DreamItems.PINE_LOG.get());
    ///            output.accept(DreamItems.PINE_WOOD.get());
    ///            output.accept(DreamItems.STRIPPED_PINE_LOG.get());
    ///            output.accept(DreamItems.STRIPPED_PINE_WOOD.get());
    ///            output.accept(DreamItems.PINE_PLANKS.get());
    ///            output.accept(DreamItems.PINE_STAIRS.get());
    ///            output.accept(DreamItems.PINE_SLAB.get());
    ///            output.accept(DreamItems.PINE_FENCE.get());
    ///            output.accept(DreamItems.PINE_FENCE_GATE.get());
    ///            output.accept(DreamItems.PINE_BUTTON.get());
    ///            output.accept(DreamItems.PINE_PRESSURE_PLATE.get());
    ///            output.accept(DreamItems.PINE_TRAPDOOR.get());
    ///            output.accept(DreamItems.PINE_DOOR.get());
    ///            output.accept(DreamItems.PINE_SIGN.get());
    ///            output.accept(DreamItems.PINE_HANGING_SIGN.get());
    ///            output.accept(DreamItems.PINE_BOAT.get());
    ///            output.accept(DreamItems.PINE_CHEST_BOAT.get());
    ///
    ///            output.accept(DreamItems.POISED_LEAVES.get());
    ///            output.accept(DreamItems.POISED_SAPLING.get());
    ///            output.accept(DreamItems.POISED_LOG.get());
    ///            output.accept(DreamItems.POISED_WOOD.get());
    ///            output.accept(DreamItems.STRIPPED_POISED_LOG.get());
    ///            output.accept(DreamItems.STRIPPED_POISED_WOOD.get());
    ///            output.accept(DreamItems.POISED_PLANKS.get());
    ///            output.accept(DreamItems.POISED_STAIRS.get());
    ///            output.accept(DreamItems.POISED_SLAB.get());
    ///            output.accept(DreamItems.POISED_FENCE.get());
    ///            output.accept(DreamItems.POISED_FENCE_GATE.get());
    ///            output.accept(DreamItems.POISED_BUTTON.get());
    ///            output.accept(DreamItems.POISED_PRESSURE_PLATE.get());
    ///            output.accept(DreamItems.POISED_TRAPDOOR.get());
    ///            output.accept(DreamItems.POISED_DOOR.get());
    ///            output.accept(DreamItems.POISED_SIGN.get());
    ///            output.accept(DreamItems.POISED_HANGING_SIGN.get());
    ///            output.accept(DreamItems.POISED_BOAT.get());
    ///            output.accept(DreamItems.POISED_CHEST_BOAT.get());
    ///
    ///            output.accept(DreamItems.BLOODWOOD_LEAVES.get());
    ///            output.accept(DreamItems.BLOODWOOD_SAPLING.get());
    ///            output.accept(DreamItems.BLOODWOOD_LOG.get());
    ///            output.accept(DreamItems.BLOODWOOD_WOOD.get());
    ///            output.accept(DreamItems.STRIPPED_BLOODWOOD_LOG.get());
    ///            output.accept(DreamItems.STRIPPED_BLOODWOOD_WOOD.get());
    ///            output.accept(DreamItems.BLOODWOOD_PLANKS.get());
    ///            output.accept(DreamItems.BLOODWOOD_STAIRS.get());
    ///            output.accept(DreamItems.BLOODWOOD_SLAB.get());
    ///            output.accept(DreamItems.BLOODWOOD_FENCE.get());
    ///            output.accept(DreamItems.BLOODWOOD_FENCE_GATE.get());
    ///            output.accept(DreamItems.BLOODWOOD_BUTTON.get());
    ///            output.accept(DreamItems.BLOODWOOD_PRESSURE_PLATE.get());
    ///            output.accept(DreamItems.BLOODWOOD_TRAPDOOR.get());
    ///            output.accept(DreamItems.BLOODWOOD_DOOR.get());
    ///            output.accept(DreamItems.BLOODWOOD_SIGN.get());
    ///            output.accept(DreamItems.BLOODWOOD_HANGING_SIGN.get());
    ///            output.accept(DreamItems.BLOODWOOD_BOAT.get());
    ///            output.accept(DreamItems.BLOODWOOD_CHEST_BOAT.get());
    ///
    ///            output.accept(DreamItems.SOUR_LEAVES.get());
    ///            output.accept(DreamItems.SOUR_SAPLING.get());
    ///            output.accept(DreamItems.SOUR_LOG.get());
    ///            output.accept(DreamItems.SOUR_WOOD.get());
    ///            output.accept(DreamItems.STRIPPED_SOUR_LOG.get());
    ///            output.accept(DreamItems.STRIPPED_SOUR_WOOD.get());
    ///            output.accept(DreamItems.SOUR_PLANKS.get());
    ///            output.accept(DreamItems.SOUR_STAIRS.get());
    ///            output.accept(DreamItems.SOUR_SLAB.get());
    ///            output.accept(DreamItems.SOUR_FENCE.get());
    ///            output.accept(DreamItems.SOUR_FENCE_GATE.get());
    ///            output.accept(DreamItems.SOUR_BUTTON.get());
    ///            output.accept(DreamItems.SOUR_PRESSURE_PLATE.get());
    ///            output.accept(DreamItems.SOUR_TRAPDOOR.get());
    ///            output.accept(DreamItems.SOUR_DOOR.get());
    ///            output.accept(DreamItems.SOUR_SIGN.get());
    ///            output.accept(DreamItems.SOUR_HANGING_SIGN.get());
    ///            output.accept(DreamItems.SOUR_BOAT.get());
    ///            output.accept(DreamItems.SOUR_CHEST_BOAT.get());
    ///
    ///            output.accept(DreamItems.FUNGUS_BLOCK.get());
    ///            output.accept(DreamItems.FUNGUS.get());
    ///            output.accept(DreamItems.FUNGUS_STEM.get());
    ///            output.accept(DreamItems.FUNGUS_HYPHAE.get());
    ///            output.accept(DreamItems.STRIPPED_FUNGUS_STEM.get());
    ///            output.accept(DreamItems.STRIPPED_FUNGUS_HYPHAE.get());
    ///            output.accept(DreamItems.FUNGUS_PLANKS.get());
    ///            output.accept(DreamItems.FUNGUS_STAIRS.get());
    ///            output.accept(DreamItems.FUNGUS_SLAB.get());
    ///            output.accept(DreamItems.FUNGUS_FENCE.get());
    ///            output.accept(DreamItems.FUNGUS_FENCE_GATE.get());
    ///            output.accept(DreamItems.FUNGUS_BUTTON.get());
    ///            output.accept(DreamItems.FUNGUS_PRESSURE_PLATE.get());
    ///            output.accept(DreamItems.FUNGUS_TRAPDOOR.get());
    ///            output.accept(DreamItems.FUNGUS_DOOR.get());
    ///            output.accept(DreamItems.FUNGUS_SIGN.get());
    ///            output.accept(DreamItems.FUNGUS_HANGING_SIGN.get());
    ///            output.accept(DreamItems.FUNGUS_BOAT.get());
    ///            output.accept(DreamItems.FUNGUS_CHEST_BOAT.get());
    ///        }).build()
    ///);

}