package com.mystanica.dreamlands.datagen;

import com.mystanica.dreamlands.init.DreamBlocks;
import net.minecraft.world.level.block.Block;

import java.util.LinkedHashMap;
import java.util.Map;
import java.util.stream.Stream;

public class DreamBlockFamilies {
    private static final Map<Block, DreamBlockFamily> FAMILIES = new LinkedHashMap<>();

    public static final DreamBlockFamily DREAMSTONE = familyBuilder(DreamBlocks.DREAMSTONE.get())
            .stone(DreamBlocks.DREAMSTONE.get())
            .stairs(DreamBlocks.DREAMSTONE_STAIRS.get())
            .slab(DreamBlocks.DREAMSTONE_SLAB.get())
            .pressurePlate(DreamBlocks.DREAMSTONE_PRESSURE_PLATE.get())
            .button(DreamBlocks.DREAMSTONE_BUTTON.get())
            .wall(DreamBlocks.DREAMSTONE_WALL.get())
            .getFamily();
    public static final DreamBlockFamily COBBLED_DREAMSTONE = familyBuilder(DreamBlocks.COBBLED_DREAMSTONE.get())
            .stone(DreamBlocks.COBBLED_DREAMSTONE.get())
            .stairs(DreamBlocks.COBBLED_DREAMSTONE_STAIRS.get())
            .slab(DreamBlocks.COBBLED_DREAMSTONE_SLAB.get())
            .wall(DreamBlocks.COBBLED_DREAMSTONE_WALL.get())
            .getFamily();
    public static final DreamBlockFamily MOSSY_COBBLED_DREAMSTONE = familyBuilder(DreamBlocks.MOSSY_COBBLED_DREAMSTONE.get())
            .stone(DreamBlocks.MOSSY_COBBLED_DREAMSTONE.get())
            .stairs(DreamBlocks.MOSSY_COBBLED_DREAMSTONE_STAIRS.get())
            .slab(DreamBlocks.MOSSY_COBBLED_DREAMSTONE_SLAB.get())
            .wall(DreamBlocks.MOSSY_COBBLED_DREAMSTONE_WALL.get())
            .getFamily();
    public static final DreamBlockFamily DREAMSTONE_BRICKS = familyBuilder(DreamBlocks.DREAMSTONE_BRICKS.get())
            .stone(DreamBlocks.DREAMSTONE_BRICKS.get())
            .stairs(DreamBlocks.DREAMSTONE_BRICK_STAIRS.get())
            .slab(DreamBlocks.DREAMSTONE_BRICK_SLAB.get())
            .wall(DreamBlocks.DREAMSTONE_BRICK_WALL.get())
            .cracked(DreamBlocks.CRACKED_DREAMSTONE_BRICKS.get())
            .chiseled(DreamBlocks.CHISELED_DREAMSTONE_BRICKS.get())
            .getFamily();
    public static final DreamBlockFamily MOSSY_DREAMSTONE_BRICKS = familyBuilder(DreamBlocks.MOSSY_DREAMSTONE_BRICKS.get())
            .stone(DreamBlocks.MOSSY_DREAMSTONE_BRICKS.get())
            .stairs(DreamBlocks.MOSSY_DREAMSTONE_BRICK_STAIRS.get())
            .slab(DreamBlocks.MOSSY_DREAMSTONE_BRICK_SLAB.get())
            .wall(DreamBlocks.MOSSY_DREAMSTONE_BRICK_WALL.get())
            .getFamily();

    public static final DreamBlockFamily DREAMY_WOOD = familyBuilder(DreamBlocks.DREAMY_PLANKS.get())
            .log(DreamBlocks.DREAMY_LOG.get(), DreamBlocks.STRIPPED_DREAMY_LOG.get())
            .wood(DreamBlocks.DREAMY_WOOD.get(), DreamBlocks.STRIPPED_DREAMY_WOOD.get())
            .planks(DreamBlocks.DREAMY_PLANKS.get())
            .stairs(DreamBlocks.DREAMY_STAIRS.get())
            .slab(DreamBlocks.DREAMY_SLAB.get())
            .fence(DreamBlocks.DREAMY_FENCE.get())
            .fenceGate(DreamBlocks.DREAMY_FENCE_GATE.get())
            .button(DreamBlocks.DREAMY_BUTTON.get())
            .pressurePlate(DreamBlocks.DREAMY_PRESSURE_PLATE.get())
            .trapdoor(DreamBlocks.DREAMY_TRAPDOOR.get())
            .door(DreamBlocks.DREAMY_DOOR.get())
            .sign(DreamBlocks.DREAMY_SIGN.get(), DreamBlocks.DREAMY_WALL_SIGN.get())
            .hangingSign(DreamBlocks.DREAMY_HANGING_SIGN.get(), DreamBlocks.DREAMY_WALL_HANGING_SIGN.get())
            .recipeGroupPrefix("wooden")
            .recipeUnlockedBy("has_planks")
            .flammable()
            .getFamily();
    public static final DreamBlockFamily ASPEN_WOOD = familyBuilder(DreamBlocks.ASPEN_PLANKS.get())
            .log(DreamBlocks.ASPEN_LOG.get(), DreamBlocks.STRIPPED_ASPEN_LOG.get())
            .wood(DreamBlocks.ASPEN_WOOD.get(), DreamBlocks.STRIPPED_ASPEN_WOOD.get())
            .planks(DreamBlocks.ASPEN_PLANKS.get())
            .stairs(DreamBlocks.ASPEN_STAIRS.get())
            .slab(DreamBlocks.ASPEN_SLAB.get())
            .fence(DreamBlocks.ASPEN_FENCE.get())
            .fenceGate(DreamBlocks.ASPEN_FENCE_GATE.get())
            .button(DreamBlocks.ASPEN_BUTTON.get())
            .pressurePlate(DreamBlocks.ASPEN_PRESSURE_PLATE.get())
            .trapdoor(DreamBlocks.ASPEN_TRAPDOOR.get())
            .door(DreamBlocks.ASPEN_DOOR.get())
            .sign(DreamBlocks.ASPEN_SIGN.get(), DreamBlocks.ASPEN_WALL_SIGN.get())
            .hangingSign(DreamBlocks.ASPEN_HANGING_SIGN.get(), DreamBlocks.ASPEN_WALL_HANGING_SIGN.get())
            .recipeGroupPrefix("wooden")
            .recipeUnlockedBy("has_planks")
            .flammable()
            .getFamily();
    public static final DreamBlockFamily EVERGREEN_WOOD = familyBuilder(DreamBlocks.EVERGREEN_PLANKS.get())
            .log(DreamBlocks.EVERGREEN_LOG.get(), DreamBlocks.STRIPPED_EVERGREEN_LOG.get())
            .wood(DreamBlocks.EVERGREEN_WOOD.get(), DreamBlocks.STRIPPED_EVERGREEN_WOOD.get())
            .planks(DreamBlocks.EVERGREEN_PLANKS.get())
            .stairs(DreamBlocks.EVERGREEN_STAIRS.get())
            .slab(DreamBlocks.EVERGREEN_SLAB.get())
            .fence(DreamBlocks.EVERGREEN_FENCE.get())
            .fenceGate(DreamBlocks.EVERGREEN_FENCE_GATE.get())
            .button(DreamBlocks.EVERGREEN_BUTTON.get())
            .pressurePlate(DreamBlocks.EVERGREEN_PRESSURE_PLATE.get())
            .trapdoor(DreamBlocks.EVERGREEN_TRAPDOOR.get())
            .door(DreamBlocks.EVERGREEN_DOOR.get())
            .sign(DreamBlocks.EVERGREEN_SIGN.get(), DreamBlocks.EVERGREEN_WALL_SIGN.get())
            .hangingSign(DreamBlocks.EVERGREEN_HANGING_SIGN.get(), DreamBlocks.EVERGREEN_WALL_HANGING_SIGN.get())
            .recipeGroupPrefix("wooden")
            .recipeUnlockedBy("has_planks")
            .flammable()
            .getFamily();
    public static final DreamBlockFamily ETHEREAL_WOOD = familyBuilder(DreamBlocks.ETHEREAL_PLANKS.get())
            .log(DreamBlocks.ETHEREAL_LOG.get(), DreamBlocks.STRIPPED_ETHEREAL_LOG.get())
            .wood(DreamBlocks.ETHEREAL_WOOD.get(), DreamBlocks.STRIPPED_ETHEREAL_WOOD.get())
            .planks(DreamBlocks.ETHEREAL_PLANKS.get())
            .stairs(DreamBlocks.ETHEREAL_STAIRS.get())
            .slab(DreamBlocks.ETHEREAL_SLAB.get())
            .fence(DreamBlocks.ETHEREAL_FENCE.get())
            .fenceGate(DreamBlocks.ETHEREAL_FENCE_GATE.get())
            .button(DreamBlocks.ETHEREAL_BUTTON.get())
            .pressurePlate(DreamBlocks.ETHEREAL_PRESSURE_PLATE.get())
            .trapdoor(DreamBlocks.ETHEREAL_TRAPDOOR.get())
            .door(DreamBlocks.ETHEREAL_DOOR.get())
            .sign(DreamBlocks.ETHEREAL_SIGN.get(), DreamBlocks.ETHEREAL_WALL_SIGN.get())
            .hangingSign(DreamBlocks.ETHEREAL_HANGING_SIGN.get(), DreamBlocks.ETHEREAL_WALL_HANGING_SIGN.get())
            .recipeGroupPrefix("wooden")
            .recipeUnlockedBy("has_planks")
            .flammable()
            .getFamily();
    public static final DreamBlockFamily CANDY_WOOD = familyBuilder(DreamBlocks.CANDY_PLANKS.get())
            .log(DreamBlocks.CANDY_LOG.get(), DreamBlocks.STRIPPED_CANDY_LOG.get())
            .wood(DreamBlocks.CANDY_WOOD.get(), DreamBlocks.STRIPPED_CANDY_WOOD.get())
            .planks(DreamBlocks.CANDY_PLANKS.get())
            .stairs(DreamBlocks.CANDY_STAIRS.get())
            .slab(DreamBlocks.CANDY_SLAB.get())
            .fence(DreamBlocks.CANDY_FENCE.get())
            .fenceGate(DreamBlocks.CANDY_FENCE_GATE.get())
            .button(DreamBlocks.CANDY_BUTTON.get())
            .pressurePlate(DreamBlocks.CANDY_PRESSURE_PLATE.get())
            .trapdoor(DreamBlocks.CANDY_TRAPDOOR.get())
            .door(DreamBlocks.CANDY_DOOR.get())
            .sign(DreamBlocks.CANDY_SIGN.get(), DreamBlocks.CANDY_WALL_SIGN.get())
            .hangingSign(DreamBlocks.CANDY_HANGING_SIGN.get(), DreamBlocks.CANDY_WALL_HANGING_SIGN.get())
            .recipeGroupPrefix("wooden")
            .recipeUnlockedBy("has_planks")
            .flammable()
            .getFamily();
    public static final DreamBlockFamily WISTERIA_WOOD = familyBuilder(DreamBlocks.WISTERIA_PLANKS.get())
            .log(DreamBlocks.WISTERIA_LOG.get(), DreamBlocks.STRIPPED_WISTERIA_LOG.get())
            .wood(DreamBlocks.WISTERIA_WOOD.get(), DreamBlocks.STRIPPED_WISTERIA_WOOD.get())
            .planks(DreamBlocks.WISTERIA_PLANKS.get())
            .stairs(DreamBlocks.WISTERIA_STAIRS.get())
            .slab(DreamBlocks.WISTERIA_SLAB.get())
            .fence(DreamBlocks.WISTERIA_FENCE.get())
            .fenceGate(DreamBlocks.WISTERIA_FENCE_GATE.get())
            .button(DreamBlocks.WISTERIA_BUTTON.get())
            .pressurePlate(DreamBlocks.WISTERIA_PRESSURE_PLATE.get())
            .trapdoor(DreamBlocks.WISTERIA_TRAPDOOR.get())
            .door(DreamBlocks.WISTERIA_DOOR.get())
            .sign(DreamBlocks.WISTERIA_SIGN.get(), DreamBlocks.WISTERIA_WALL_SIGN.get())
            .hangingSign(DreamBlocks.WISTERIA_HANGING_SIGN.get(), DreamBlocks.WISTERIA_WALL_HANGING_SIGN.get())
            .recipeGroupPrefix("wooden")
            .recipeUnlockedBy("has_planks")
            .flammable()
            .getFamily();
    public static final DreamBlockFamily MYSTICAL_WOOD = familyBuilder(DreamBlocks.MYSTICAL_PLANKS.get())
            .log(DreamBlocks.MYSTICAL_LOG.get(), DreamBlocks.STRIPPED_MYSTICAL_LOG.get())
            .wood(DreamBlocks.MYSTICAL_WOOD.get(), DreamBlocks.STRIPPED_MYSTICAL_WOOD.get())
            .planks(DreamBlocks.MYSTICAL_PLANKS.get())
            .stairs(DreamBlocks.MYSTICAL_STAIRS.get())
            .slab(DreamBlocks.MYSTICAL_SLAB.get())
            .fence(DreamBlocks.MYSTICAL_FENCE.get())
            .fenceGate(DreamBlocks.MYSTICAL_FENCE_GATE.get())
            .button(DreamBlocks.MYSTICAL_BUTTON.get())
            .pressurePlate(DreamBlocks.MYSTICAL_PRESSURE_PLATE.get())
            .trapdoor(DreamBlocks.MYSTICAL_TRAPDOOR.get())
            .door(DreamBlocks.MYSTICAL_DOOR.get())
            .sign(DreamBlocks.MYSTICAL_SIGN.get(), DreamBlocks.MYSTICAL_WALL_SIGN.get())
            .hangingSign(DreamBlocks.MYSTICAL_HANGING_SIGN.get(), DreamBlocks.MYSTICAL_WALL_HANGING_SIGN.get())
            .recipeGroupPrefix("wooden")
            .recipeUnlockedBy("has_planks")
            .flammable()
            .getFamily();
    public static final DreamBlockFamily MUSHROOM_WOOD = familyBuilder(DreamBlocks.MUSHROOM_PLANKS.get())
            .log(DreamBlocks.MUSHROOM_STEM.get(), DreamBlocks.STRIPPED_MUSHROOM_STEM.get())
            .wood(DreamBlocks.MUSHROOM_HYPHAE.get(), DreamBlocks.STRIPPED_MUSHROOM_HYPHAE.get())
            .planks(DreamBlocks.MUSHROOM_PLANKS.get())
            .stairs(DreamBlocks.MUSHROOM_STAIRS.get())
            .slab(DreamBlocks.MUSHROOM_SLAB.get())
            .fence(DreamBlocks.MUSHROOM_FENCE.get())
            .fenceGate(DreamBlocks.MUSHROOM_FENCE_GATE.get())
            .button(DreamBlocks.MUSHROOM_BUTTON.get())
            .pressurePlate(DreamBlocks.MUSHROOM_PRESSURE_PLATE.get())
            .trapdoor(DreamBlocks.MUSHROOM_TRAPDOOR.get())
            .door(DreamBlocks.MUSHROOM_DOOR.get())
            .sign(DreamBlocks.MUSHROOM_SIGN.get(), DreamBlocks.MUSHROOM_WALL_SIGN.get())
            .hangingSign(DreamBlocks.MUSHROOM_HANGING_SIGN.get(), DreamBlocks.MUSHROOM_WALL_HANGING_SIGN.get())
            .recipeGroupPrefix("wooden")
            .recipeUnlockedBy("has_planks")
            .flammable()
            .getFamily();

    ///public static final DreamBlockFamily GRIMSTONE = familyBuilder(DreamBlocks.GRIMSTONE.get())
    ///        .stone(DreamBlocks.GRIMSTONE.get())
    ///        .stairs(DreamBlocks.GRIMSTONE_STAIRS.get())
    ///        .slab(DreamBlocks.GRIMSTONE_SLAB.get())
    ///        .pressurePlate(DreamBlocks.GRIMSTONE_PRESSURE_PLATE.get())
    ///        .button(DreamBlocks.GRIMSTONE_BUTTON.get())
    ///        .wall(DreamBlocks.GRIMSTONE_WALL.get())
    ///        .getFamily();
    ///public static final DreamBlockFamily COBBLED_GRIMSTONE = familyBuilder(DreamBlocks.COBBLED_GRIMSTONE.get())
    ///        .stone(DreamBlocks.COBBLED_GRIMSTONE.get())
    ///        .stairs(DreamBlocks.COBBLED_GRIMSTONE_STAIRS.get())
    ///        .slab(DreamBlocks.COBBLED_GRIMSTONE_SLAB.get())
    ///        .wall(DreamBlocks.COBBLED_GRIMSTONE_WALL.get())
    ///        .getFamily();
    ///public static final DreamBlockFamily MOSSY_COBBLED_GRIMSTONE = familyBuilder(DreamBlocks.MOSSY_COBBLED_GRIMSTONE.get())
    ///        .stone(DreamBlocks.MOSSY_COBBLED_GRIMSTONE.get())
    ///        .stairs(DreamBlocks.MOSSY_COBBLED_GRIMSTONE_STAIRS.get())
    ///        .slab(DreamBlocks.MOSSY_COBBLED_GRIMSTONE_SLAB.get())
    ///        .wall(DreamBlocks.MOSSY_COBBLED_GRIMSTONE_WALL.get())
    ///        .getFamily();
    ///public static final DreamBlockFamily GRIMSTONE_BRICKS = familyBuilder(DreamBlocks.GRIMSTONE_BRICKS.get())
    ///        .stone(DreamBlocks.GRIMSTONE_BRICKS.get())
    ///        .stairs(DreamBlocks.GRIMSTONE_BRICK_STAIRS.get())
    ///        .slab(DreamBlocks.GRIMSTONE_BRICK_SLAB.get())
    ///        .wall(DreamBlocks.GRIMSTONE_BRICK_WALL.get())
    ///        .cracked(DreamBlocks.CRACKED_GRIMSTONE_BRICKS.get())
    ///        .chiseled(DreamBlocks.CHISELED_GRIMSTONE_BRICKS.get())
    ///        .getFamily();
    ///public static final DreamBlockFamily MOSSY_GRIMSTONE_BRICKS = familyBuilder(DreamBlocks.MOSSY_GRIMSTONE_BRICKS.get())
    ///        .stone(DreamBlocks.MOSSY_GRIMSTONE_BRICKS.get())
    ///        .stairs(DreamBlocks.MOSSY_GRIMSTONE_BRICK_STAIRS.get())
    ///        .slab(DreamBlocks.MOSSY_GRIMSTONE_BRICK_SLAB.get())
    ///        .wall(DreamBlocks.MOSSY_GRIMSTONE_BRICK_WALL.get())
    ///        .getFamily();
    ///public static final DreamBlockFamily GLOOMY_WOOD = familyBuilder(DreamBlocks.GLOOMY_PLANKS.get())
    ///        .log(DreamBlocks.GLOOMY_LOG.get(), DreamBlocks.STRIPPED_GLOOMY_LOG.get())
    ///        .wood(DreamBlocks.GLOOMY_WOOD.get(), DreamBlocks.STRIPPED_GLOOMY_WOOD.get())
    ///        .planks(DreamBlocks.GLOOMY_PLANKS.get())
    ///        .stairs(DreamBlocks.GLOOMY_STAIRS.get())
    ///        .slab(DreamBlocks.GLOOMY_SLAB.get())
    ///        .fence(DreamBlocks.GLOOMY_FENCE.get())
    ///        .fenceGate(DreamBlocks.GLOOMY_FENCE_GATE.get())
    ///        .button(DreamBlocks.GLOOMY_BUTTON.get())
    ///        .pressurePlate(DreamBlocks.GLOOMY_PRESSURE_PLATE.get())
    ///        .trapdoor(DreamBlocks.GLOOMY_TRAPDOOR.get())
    ///        .door(DreamBlocks.GLOOMY_DOOR.get())
    ///        .sign(DreamBlocks.GLOOMY_SIGN.get(), DreamBlocks.GLOOMY_WALL_SIGN.get())
    ///        .hangingSign(DreamBlocks.GLOOMY_HANGING_SIGN.get(), DreamBlocks.GLOOMY_WALL_HANGING_SIGN.get())
    ///        .recipeGroupPrefix("wooden")
    ///        .recipeUnlockedBy("has_planks")
    ///        .flammable()
    ///        .getFamily();
    ///public static final DreamBlockFamily GRIMWOOD_WOOD = familyBuilder(DreamBlocks.GRIMWOOD_PLANKS.get())
    ///        .log(DreamBlocks.GRIMWOOD_LOG.get(), DreamBlocks.STRIPPED_GRIMWOOD_LOG.get())
    ///        .wood(DreamBlocks.GRIMWOOD_WOOD.get(), DreamBlocks.STRIPPED_GRIMWOOD_WOOD.get())
    ///        .planks(DreamBlocks.GRIMWOOD_PLANKS.get())
    ///        .stairs(DreamBlocks.GRIMWOOD_STAIRS.get())
    ///        .slab(DreamBlocks.GRIMWOOD_SLAB.get())
    ///        .fence(DreamBlocks.GRIMWOOD_FENCE.get())
    ///        .fenceGate(DreamBlocks.GRIMWOOD_FENCE_GATE.get())
    ///        .button(DreamBlocks.GRIMWOOD_BUTTON.get())
    ///        .pressurePlate(DreamBlocks.GRIMWOOD_PRESSURE_PLATE.get())
    ///        .trapdoor(DreamBlocks.GRIMWOOD_TRAPDOOR.get())
    ///        .door(DreamBlocks.GRIMWOOD_DOOR.get())
    ///        .sign(DreamBlocks.GRIMWOOD_SIGN.get(), DreamBlocks.GRIMWOOD_WALL_SIGN.get())
    ///        .hangingSign(DreamBlocks.GRIMWOOD_HANGING_SIGN.get(), DreamBlocks.GRIMWOOD_WALL_HANGING_SIGN.get())
    ///        .recipeGroupPrefix("wooden")
    ///        .recipeUnlockedBy("has_planks")
    ///        .flammable()
    ///        .getFamily();
    ///public static final DreamBlockFamily DEAD_WOOD = familyBuilder(DreamBlocks.DEAD_PLANKS.get())
    ///        .log(DreamBlocks.DEAD_LOG.get(), DreamBlocks.STRIPPED_DEAD_LOG.get())
    ///        .wood(DreamBlocks.DEAD_WOOD.get(), DreamBlocks.STRIPPED_DEAD_WOOD.get())
    ///        .planks(DreamBlocks.DEAD_PLANKS.get())
    ///        .stairs(DreamBlocks.DEAD_STAIRS.get())
    ///        .slab(DreamBlocks.DEAD_SLAB.get())
    ///        .fence(DreamBlocks.DEAD_FENCE.get())
    ///        .fenceGate(DreamBlocks.DEAD_FENCE_GATE.get())
    ///        .button(DreamBlocks.DEAD_BUTTON.get())
    ///        .pressurePlate(DreamBlocks.DEAD_PRESSURE_PLATE.get())
    ///        .trapdoor(DreamBlocks.DEAD_TRAPDOOR.get())
    ///        .door(DreamBlocks.DEAD_DOOR.get())
    ///        .sign(DreamBlocks.DEAD_SIGN.get(), DreamBlocks.DEAD_WALL_SIGN.get())
    ///        .hangingSign(DreamBlocks.DEAD_HANGING_SIGN.get(), DreamBlocks.DEAD_WALL_HANGING_SIGN.get())
    ///        .recipeGroupPrefix("wooden")
    ///        .recipeUnlockedBy("has_planks")
    ///        .flammable()
    ///        .getFamily();
    ///public static final DreamBlockFamily PINE_WOOD = familyBuilder(DreamBlocks.PINE_PLANKS.get())
    ///        .log(DreamBlocks.PINE_LOG.get(), DreamBlocks.STRIPPED_PINE_LOG.get())
    ///        .wood(DreamBlocks.PINE_WOOD.get(), DreamBlocks.STRIPPED_PINE_WOOD.get())
    ///        .planks(DreamBlocks.PINE_PLANKS.get())
    ///        .stairs(DreamBlocks.PINE_STAIRS.get())
    ///        .slab(DreamBlocks.PINE_SLAB.get())
    ///        .fence(DreamBlocks.PINE_FENCE.get())
    ///        .fenceGate(DreamBlocks.PINE_FENCE_GATE.get())
    ///        .button(DreamBlocks.PINE_BUTTON.get())
    ///        .pressurePlate(DreamBlocks.PINE_PRESSURE_PLATE.get())
    ///        .trapdoor(DreamBlocks.PINE_TRAPDOOR.get())
    ///        .door(DreamBlocks.PINE_DOOR.get())
    ///        .sign(DreamBlocks.PINE_SIGN.get(), DreamBlocks.PINE_WALL_SIGN.get())
    ///        .hangingSign(DreamBlocks.PINE_HANGING_SIGN.get(), DreamBlocks.PINE_WALL_HANGING_SIGN.get())
    ///        .recipeGroupPrefix("wooden")
    ///        .recipeUnlockedBy("has_planks")
    ///        .flammable()
    ///        .getFamily();
    ///public static final DreamBlockFamily POISED_WOOD = familyBuilder(DreamBlocks.POISED_PLANKS.get())
    ///        .log(DreamBlocks.POISED_LOG.get(), DreamBlocks.STRIPPED_POISED_LOG.get())
    ///        .wood(DreamBlocks.POISED_WOOD.get(), DreamBlocks.STRIPPED_POISED_WOOD.get())
    ///        .planks(DreamBlocks.POISED_PLANKS.get())
    ///        .stairs(DreamBlocks.POISED_STAIRS.get())
    ///        .slab(DreamBlocks.POISED_SLAB.get())
    ///        .fence(DreamBlocks.POISED_FENCE.get())
    ///        .fenceGate(DreamBlocks.POISED_FENCE_GATE.get())
    ///        .button(DreamBlocks.POISED_BUTTON.get())
    ///        .pressurePlate(DreamBlocks.POISED_PRESSURE_PLATE.get())
    ///        .trapdoor(DreamBlocks.POISED_TRAPDOOR.get())
    ///        .door(DreamBlocks.POISED_DOOR.get())
    ///        .sign(DreamBlocks.POISED_SIGN.get(), DreamBlocks.POISED_WALL_SIGN.get())
    ///        .hangingSign(DreamBlocks.POISED_HANGING_SIGN.get(), DreamBlocks.POISED_WALL_HANGING_SIGN.get())
    ///        .recipeGroupPrefix("wooden")
    ///        .recipeUnlockedBy("has_planks")
    ///        .flammable()
    ///        .getFamily();
    ///public static final DreamBlockFamily BLOODWOOD_WOOD = familyBuilder(DreamBlocks.BLOODWOOD_PLANKS.get())
    ///        .log(DreamBlocks.BLOODWOOD_LOG.get(), DreamBlocks.STRIPPED_BLOODWOOD_LOG.get())
    ///        .wood(DreamBlocks.BLOODWOOD_WOOD.get(), DreamBlocks.STRIPPED_BLOODWOOD_WOOD.get())
    ///        .planks(DreamBlocks.BLOODWOOD_PLANKS.get())
    ///        .stairs(DreamBlocks.BLOODWOOD_STAIRS.get())
    ///        .slab(DreamBlocks.BLOODWOOD_SLAB.get())
    ///        .fence(DreamBlocks.BLOODWOOD_FENCE.get())
    ///        .fenceGate(DreamBlocks.BLOODWOOD_FENCE_GATE.get())
    ///        .button(DreamBlocks.BLOODWOOD_BUTTON.get())
    ///        .pressurePlate(DreamBlocks.BLOODWOOD_PRESSURE_PLATE.get())
    ///        .trapdoor(DreamBlocks.BLOODWOOD_TRAPDOOR.get())
    ///        .door(DreamBlocks.BLOODWOOD_DOOR.get())
    ///        .sign(DreamBlocks.BLOODWOOD_SIGN.get(), DreamBlocks.BLOODWOOD_WALL_SIGN.get())
    ///        .hangingSign(DreamBlocks.BLOODWOOD_HANGING_SIGN.get(), DreamBlocks.BLOODWOOD_WALL_HANGING_SIGN.get())
    ///        .recipeGroupPrefix("wooden")
    ///        .recipeUnlockedBy("has_planks")
    ///        .flammable()
    ///        .getFamily();
    ///public static final DreamBlockFamily SOUR_WOOD = familyBuilder(DreamBlocks.SOUR_PLANKS.get())
    ///        .log(DreamBlocks.SOUR_LOG.get(), DreamBlocks.STRIPPED_SOUR_LOG.get())
    ///        .wood(DreamBlocks.SOUR_WOOD.get(), DreamBlocks.STRIPPED_SOUR_WOOD.get())
    ///        .planks(DreamBlocks.SOUR_PLANKS.get())
    ///        .stairs(DreamBlocks.SOUR_STAIRS.get())
    ///        .slab(DreamBlocks.SOUR_SLAB.get())
    ///        .fence(DreamBlocks.SOUR_FENCE.get())
    ///        .fenceGate(DreamBlocks.SOUR_FENCE_GATE.get())
    ///        .button(DreamBlocks.SOUR_BUTTON.get())
    ///        .pressurePlate(DreamBlocks.SOUR_PRESSURE_PLATE.get())
    ///        .trapdoor(DreamBlocks.SOUR_TRAPDOOR.get())
    ///        .door(DreamBlocks.SOUR_DOOR.get())
    ///        .sign(DreamBlocks.SOUR_SIGN.get(), DreamBlocks.SOUR_WALL_SIGN.get())
    ///        .hangingSign(DreamBlocks.SOUR_HANGING_SIGN.get(), DreamBlocks.SOUR_WALL_HANGING_SIGN.get())
    ///        .recipeGroupPrefix("wooden")
    ///        .recipeUnlockedBy("has_planks")
    ///        .flammable()
    ///        .getFamily();
    ///public static final DreamBlockFamily FUNGUS_WOOD = familyBuilder(DreamBlocks.FUNGUS_PLANKS.get())
    ///        .log(DreamBlocks.FUNGUS_STEM.get(), DreamBlocks.STRIPPED_FUNGUS_STEM.get())
    ///        .wood(DreamBlocks.FUNGUS_HYPHAE.get(), DreamBlocks.STRIPPED_FUNGUS_HYPHAE.get())
    ///        .planks(DreamBlocks.FUNGUS_PLANKS.get())
    ///        .stairs(DreamBlocks.FUNGUS_STAIRS.get())
    ///        .slab(DreamBlocks.FUNGUS_SLAB.get())
    ///        .fence(DreamBlocks.FUNGUS_FENCE.get())
    ///        .fenceGate(DreamBlocks.FUNGUS_FENCE_GATE.get())
    ///        .button(DreamBlocks.FUNGUS_BUTTON.get())
    ///        .pressurePlate(DreamBlocks.FUNGUS_PRESSURE_PLATE.get())
    ///        .trapdoor(DreamBlocks.FUNGUS_TRAPDOOR.get())
    ///        .door(DreamBlocks.FUNGUS_DOOR.get())
    ///        .sign(DreamBlocks.FUNGUS_SIGN.get(), DreamBlocks.FUNGUS_WALL_SIGN.get())
    ///        .hangingSign(DreamBlocks.FUNGUS_HANGING_SIGN.get(), DreamBlocks.FUNGUS_WALL_HANGING_SIGN.get())
    ///        .recipeGroupPrefix("wooden")
    ///        .recipeUnlockedBy("has_planks")
    ///        .flammable()
    ///        .getFamily();

    private static DreamBlockFamily.Builder familyBuilder(Block block) {
        DreamBlockFamily.Builder builder = new DreamBlockFamily.Builder(block);
        FAMILIES.put(block, builder.getFamily());
        return builder;
    }

    public static Stream<DreamBlockFamily> getAllFamilies() {
        return FAMILIES.values().stream();
    }

}